name: Build LaTeX Resume

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-full

      - name: Compile LaTeX Document
        run: pdflatex resume.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Resume PDF
          path: resume.pdf
